const NETACAD_ANSWERS = [
  {
    q: "Which statement describes a difference between the Cisco ASA IOS CLI feature and the router IOS CLI feature?",
    a: [
      "To use a show command in a general configuration mode, ASA can use the command directly whereas a router will need to enter the do command before issuing the show command.",
    ],
  },
  {
    q: "Refer to the exhibit. A network administrator is configuring AAA implementation on an ASA device. What does the option link3 indicate?",
    a: ["the interface name"],
  },
  {
    q: "What provides both secure segmentation and threat defense in a Secure Data Center solution?",
    a: ["Adaptive Security Appliance"],
  },
  {
    q: "What are the three core components of the Cisco Secure Data Center solution? (Choose three.)",
    a: ["secure segmentation", "visibility", "threat defense"],
  },
  {
    q: "What are three characteristics of ASA transparent mode? (Choose three.)",
    a: [
      "This mode does not support VPNs, QoS, or DHCP Relay.",
      "This mode is referred to as a “bump in the wire.”",
      "In this mode the ASA is invisible to an attacker.",
    ],
  },
  {
    q: "What is needed to allow specific traffic that is sourced on the outside network of an ASA firewall to reach an internal network?",
    a: ["ACL"],
  },
  {
    q: "What will be the result of failed login attempts if the following command is entered into a router?",
    a: [
      "All login attempts will be blocked for 150 seconds if there are 4 failed attempts within 90 seconds.",
    ],
  },
  {
    q: "Which two tasks are associated with router hardening? (Choose two.)",
    a: [
      "disabling unused ports and interfaces",
      "securing administrative access",
    ],
  },
  {
    q: "Which threat protection capability is provided by Cisco ESA?",
    a: ["spam protection"],
  },
  {
    q: "What are two security measures used to protect endpoints in the borderless network? (Choose two.)",
    a: ["denylisting", "DLP"],
  },
  {
    q: "Which three types of traffic are allowed when the authentication port-control auto command has been issued and the client has not yet been authenticated? (Choose three.)",
    a: ["CDP", "STP", "EAPOL"],
  },
  {
    q: "Which statement describes a characteristic of the IKE protocol?",
    a: [
      "It uses UDP port 500 to exchange IKE information between the security gateways.",
    ],
  },
  {
    q: "Which action do IPsec peers take during the IKE Phase 2 exchange?",
    a: ["negotiation of IPsec policy"],
  },
  {
    q: "What are two hashing algorithms used with IPsec AH to guarantee authenticity? (Choose two.)",
    a: ["SHA", "MD5"],
  },
  {
    q: "Which command raises the privilege level of the ping command to 7?",
    a: ["privilege exec level 7 ping"],
  },
  {
    q: "What is a characteristic of a role-based CLI view of router configuration?",
    a: ["A single CLI view can be shared within multiple superviews."],
  },
  {
    q: "What is a limitation to using OOB management on a large enterprise network?",
    a: ["All devices appear to be attached to a single management network."],
  },
  {
    q: "Refer to the exhibit. A corporate network is using NTP to synchronize the time across devices. What can be determined from the displayed output?",
    a: [
      "Router03 is a stratum 2 device that can provide NTP service to other devices in the network.",
    ],
  },
  {
    q: "Refer to the exhibit. Which two conclusions can be drawn from the syslog message that was generated by the router? (Choose two.)",
    a: [
      "This message indicates that service timestamps have been configured.",
      "This message is a level 5 notification message.",
    ],
  },
  {
    q: "Which two types of hackers are typically classified as grey hat hackers? (Choose two.)",
    a: ["hacktivists", "vulnerability brokers"],
  },
  {
    q: "Which type of packet is unable to be filtered by an outbound ACL?",
    a: ["router-generated packet"],
  },
  {
    q: "Which command is used to activate an IPv6 ACL named ENG_ACL on an interface so that the router filters traffic prior to accessing the routing table?",
    a: ["ipv6 traffic-filter ENG_ACL in"],
  },
  {
    q: "What technology has a function of using trusted third-party protocols to issue credentials that are accepted as an authoritative identity?",
    a: ["PKI certificates"],
  },
  {
    q: "What are two methods to maintain certificate revocation status? (Choose two.)",
    a: ["OCSP", "CRL"],
  },
  {
    q: "Which protocol is an IETF standard that defines the PKI digital certificate format?",
    a: ["X.509"],
  },
  {
    q: "A network administrator is configuring DAI on a switch. Which command should be used on the uplink interface that connects to a router?",
    a: ["ip arp inspection trust"],
  },
  {
    q: "What is the best way to prevent a VLAN hopping attack?",
    a: [
      "Disable trunk negotiation for trunk ports and statically set nontrunk ports as access ports.",
    ],
  },
  {
    q: "What would be the primary reason an attacker would launch a MAC address overflow attack?",
    a: [
      "so that the attacker can see frames that are destined for other hosts",
    ],
  },
  {
    q: "What is the main difference between the implementation of IDS and IPS devices?",
    a: [
      "An IDS would allow malicious traffic to pass before it is addressed, whereas an IPS stops it immediately.",
    ],
  },
  {
    q: "Which attack is defined as an attempt to exploit software vulnerabilities that are unknown or undisclosed by the vendor?",
    a: ["zero-day"],
  },
  {
    q: "What are the three signature levels provided by Snort IPS on the 4000 Series ISR? (Choose three.)",
    a: ["security", "connectivity", "balanced"],
  },
  {
    q: "What are three attributes of IPS signatures? (Choose three.)",
    a: ["action", "trigger", "type"],
  },
  {
    q: "Which two features are included by both TACACS+ and RADIUS protocols? (Choose two.)",
    a: ["password encryption", "utilization of transport layer protocols"],
  },
  {
    q: "What function is provided by the RADIUS protocol?",
    a: ["RADIUS provides separate ports for authorization and accounting."],
  },
  {
    q: "What are three characteristics of the RADIUS protocol? (Choose three.)",
    a: [
      "uses UDP ports for authentication and accounting",
      "supports 802.1X and SIP",
      "is an open RFC standard AAA protocol",
    ],
  },
  {
    q: "Which zone-based policy firewall zone is system-defined and applies to traffic destined for the router or originating from the router?",
    a: ["self zone"],
  },
  {
    q: "What are two benefits of using a ZPF rather than a Classic Firewall? (Choose two.)",
    a: [
      "The ZPF is not dependent on ACLs.",
      "ZPF policies are easy to read and troubleshoot.",
    ],
  },
  {
    q: "How does a firewall handle traffic when it is originating from the private network and traveling to the DMZ network?",
    a: ["The traffic is usually permitted with little or no restrictions."],
  },
  {
    q: "Which two protocols generate connection information within a state table and are supported for stateful filtering? (Choose two.)",
    a: ["TCP", "HTTP"],
  },
  {
    q: "Which type of firewall is supported by most routers and is the easiest to implement?",
    a: ["stateless firewall"],
  },
  {
    q: "What network testing tool would an administrator use to assess and validate system configurations against security policies and compliance standards?",
    a: ["Tripwire"],
  },
  {
    q: "What type of network security test can detect and report changes made to network systems?",
    a: ["integrity checking"],
  },
  {
    q: "What network security testing tool has the ability to provide details on the source of suspicious network activity?",
    a: ["SIEM"],
  },
  {
    q: "How does a Caesar cipher work on a message?",
    a: [
      "Letters of the message are replaced by another letter that is a set number of places away in the alphabet.",
    ],
  },
  {
    q: "What is the main factor that ensures the security of encryption of modern algorithms?",
    a: ["secrecy of the keys"],
  },
  { q: "Which algorithm can ensure data integrity?", a: ["MD5"] },
  {
    q: "A company implements a security policy that ensures that a file sent from the headquarters office to the branch office can only be opened with a predetermined code. This code is changed every day. Which two algorithms can be used to achieve this task? (Choose two.)",
    a: ["3DES", "AES"],
  },
  {
    q: "A network technician has been asked to design a virtual private network between two branch routers. Which type of cryptographic key should be used in this scenario?",
    a: ["symmetric key"],
  },
  {
    q: "Which two options can limit the information discovered from port scanning? (Choose two.)",
    a: ["intrusion prevention system", "firewall"],
  },
  {
    q: "An administrator discovers that a user is accessing a newly established website that may be detrimental to company security. What action should the administrator take first in terms of the security policy?",
    a: [
      "Revise the AUP immediately and get all users to sign the updated AUP.",
    ],
  },
  {
    q: "If AAA is already enabled, which three CLI steps are required to configure a router with a specific view? (Choose three.)",
    a: [
      "Create a view using the parser viewcommand.",
      "Assign a secret password to the view.",
      "Assign commands to the view.",
    ],
  },
  {
    q: "ACLs are used primarily to filter traffic. What are two additional uses of ACLs? (Choose two.):",
    a: ["specifying internal hosts for NAT", "identifying traffic for QoS"],
  },
  {
    q: "What two features are added in SNMPv3 to address the weaknesses of previous versions of SNMP? (Choose two.)",
    a: ["authentication", "encryption"],
  },
  {
    q: "What network testing tool is used for password auditing and recovery?",
    a: ["L0phtcrack"],
  },
  {
    q: "Which type of firewall makes use of a server to connect to destination devices on behalf of clients?",
    a: ["proxy firewall"],
  },
  {
    q: "Refer to the exhibit. What will be displayed in the output of the show running-config object command after the exhibited configuration commands are entered on an ASA 5506-X?",
    a: ["range 192.168.1.10 192.168.1.20"],
  },
  {
    q: "Refer to the exhibit. According to the command output, which three statements are true about the DHCP options entered on the ASA? (Choose three.)",
    a: [
      "The dhcpd address [ start-of-pool ]-[ end-of-pool ] inside command was issued to enable the DHCP server.",
      "The dhcpd enable inside command was issued to enable the DHCP server.",
      "The dhcpd auto-config outside command was issued to enable the DHCP client.",
    ],
  },
  {
    q: "Which two statements describe the characteristics of symmetric algorithms? (Choose two.)",
    a: [
      "They are commonly used with VPN traffic.",
      "They are referred to as a pre-shared key or secret key.",
    ],
  },
  {
    q: "A web server administrator is configuring access settings to require users to authenticate first before accessing certain web pages. Which requirement of information security is addressed through the configuration?",
    a: ["confidentiality"],
  },
  {
    q: "The use of 3DES within the IPsec framework is an example of which of the five IPsec building blocks?",
    a: ["confidentiality"],
  },
  {
    q: "What function is provided by Snort as part of the Security Onion?",
    a: [
      "to generate network intrusion alerts by the use of rules and signatures",
    ],
  },
  {
    q: "What are two drawbacks to using HIPS? (Choose two.)",
    a: [
      "With HIPS, the network administrator must verify support for all the different operating systems used in the network.",
      "HIPS has difficulty constructing an accurate network picture or coordinating events that occur across the entire network.",
    ],
  },
  {
    q: "In an AAA-enabled network, a user issues the configure terminal command from the privileged executive mode of operation. What AAA function is at work if this command is rejected?",
    a: ["authorization"],
  },
  {
    q: "A company has a file server that shares a folder named Public. The network security policy specifies that the Public folder is assigned Read-Only rights to anyone who can log into the server while the Edit rights are assigned only to the network admin group. Which component is addressed in the AAA network service framework?",
    a: ["authorization"],
  },
  {
    q: "What is a characteristic of a DMZ zone?",
    a: [
      "Traffic originating from the outside network going to the DMZ network is selectively permitted.",
    ],
  },
  {
    q: "Which measure can a security analyst take to perform effective security monitoring against network traffic encrypted by SSL technology?",
    a: ["Deploy a Cisco SSL Appliance."],
  },
  {
    q: "What security countermeasure is effective for preventing CAM table overflow attacks?",
    a: ["port security"],
  },
  {
    q: "What are two examples of DoS attacks? (Choose two.)",
    a: ["ping of death", "buffer overflow"],
  },
  {
    q: "Which method is used to identify interesting traffic needed to create an IKE phase 1 tunnel?",
    a: ["a permit access list entry"],
  },
  {
    q: "When the CLI is used to configure an ISR for a site-to-site VPN connection, which two items must be specified to enable a crypto map policy? (Choose two.)",
    a: ["the peer", "a valid access list"],
  },
  {
    q: "How does a firewall handle traffic when it is originating from the public network and traveling to the DMZ network?",
    a: [
      "Traffic that is originating from the public network is inspected and selectively permitted when traveling to the DMZ network.",
    ],
  },
  {
    q: "A client connects to a Web server. Which component of this HTTP connection is not examined by a stateful firewall?",
    a: ["the actual contents of the HTTP connection"],
  },
  {
    q: "Which network monitoring technology uses VLANs to monitor traffic on remote switches?",
    a: ["RSPAN"],
  },
  {
    q: "Which rule action will cause Snort IPS to block and log a packet?",
    a: ["drop"],
  },
  {
    q: "What is typically used to create a security trap in the data center facility?",
    a: ["IDs, biometrics, and two access doors"],
  },
  {
    q: "A company is concerned with leaked and stolen corporate data on hard copies. Which data loss mitigation technique could help with this situation?",
    a: ["shredding"],
  },
  {
    q: "Upon completion of a network security course, a student decides to pursue a career in cryptanalysis. What job would the student be doing as a cryptanalyst?",
    a: ["cracking code without access to the shared secret key"],
  },
  {
    q: "What command is used on a switch to set the port access entity type so the interface acts only as an authenticator and will not respond to any messages meant for a supplicant?",
    a: ["dot1x pae authenticator"],
  },
  {
    q: "What are two disadvantages of using an IDS? (Choose two.)",
    a: [
      "The IDS does not stop malicious traffic.",
      "The IDS requires other devices to respond to attacks.",
    ],
  },
  {
    q: "Refer to the exhibit. The ip verify source command is applied on untrusted interfaces. Which type of attack is mitigated by using this configuration?",
    a: ["MAC and IP address spoofing"],
  },
  {
    q: "What ports can receive forwarded traffic from an isolated port that is part of a PVLAN?",
    a: ["only promiscuous ports"],
  },
  {
    q: "A user complains about being locked out of a device after too many unsuccessful AAA login attempts. What could be used by the network administrator to provide a secure authentication access method without locking a user out of a device?",
    a: ["Use the login delay command for authentication attempts."],
  },
  {
    q: "What are two drawbacks in assigning user privilege levels on a Cisco router? (Choose two.)",
    a: [
      "Assigning a command with multiple keywords allows access to all commands using those keywords.",
      "Commands from a lower level are always executable at a higher level.",
    ],
  },
  {
    q: "Refer to the exhibit. Which conclusion can be made from the show crypto map command output that is shown on R1?",
    a: ["The crypto map has not yet been applied to an interface."],
  },
  {
    q: "What are two reasons to enable OSPF routing protocol authentication on a network? (Choose two.)",
    a: [
      "to prevent data traffic from being redirected and then discarded",
      "to prevent redirection of data traffic to an insecure link",
    ],
  },
  {
    q: "Which three functions are provided by the syslog logging service? (Choose three.)",
    a: [
      "gathering logging information",
      "specifying where captured information is stored",
      "distinguishing between information to be captured and information to be ignored",
    ],
  },
  {
    q: "What two ICMPv6 message types must be permitted through IPv6 access control lists to allow resolution of Layer 3 addresses to Layer 2 MAC addresses? (Choose two.)",
    a: ["neighbor solicitations", "neighbor advertisements"],
  },
  {
    q: "Which three services are provided through digital signatures? (Choose three.)",
    a: ["authenticity", "nonrepudiation", "integrity"],
  },
  {
    q: "A technician is to document the current configurations of all network devices in a college, including those in off-site buildings. Which protocol would be best to use to securely access the network devices?",
    a: ["SSH"],
  },
  {
    q: "An administrator is trying to develop a BYOD security policy for employees that are bringing a wide range of devices to connect to the company network. Which three objectives must the BYOD security policy address? (Choose three.)",
    a: [
      "Rights and activities permitted on the corporate network must be defined.",
      "Safeguards must be put in place for any personal device being compromised.",
      "The level of access of employees when connecting to the corporate network must be defined.",
    ],
  },
  {
    q: "What is the function of the pass action on a Cisco IOS Zone-Based Policy Firewall?",
    a: ["forwarding traffic from one zone to another"],
  },
  {
    q: "Refer to the exhibit. Based on the security levels of the interfaces on ASA1, what traffic will be allowed on the interfaces?",
    a: ["Traffic from the LAN and DMZ can access the Internet."],
  },
  {
    q: "What network testing tool can be used to identify network layer protocols running on a host?",
    a: ["Nmap"],
  },
  {
    q: "In the implementation of security on multiple devices, how do ASA ACLs differ from Cisco IOS ACLs?",
    a: [
      "Cisco IOS ACLs are configured with a wildcard mask and Cisco ASA ACLs are configured with a subnet mask.",
    ],
  },
  {
    q: "Which statement describes an important characteristic of a site-to-site VPN?",
    a: ["It must be statically set up."],
  },
  {
    q: "Which two options are security best practices that help mitigate BYOD risks? (Choose two.)",
    a: [
      "Keep the device OS and software updated.",
      "Only turn on Wi-Fi when using the wireless network.",
    ],
  },
  {
    q: "Refer to the exhibit. A network administrator configures AAA authentication on R1. Which statement describes the effect of the keyword single-connection in the configuration?",
    a: [
      "The authentication performance is enhanced by keeping the connection to the TACACS+ server open.",
    ],
  },
  {
    q: "A recently created ACL is not working as expected. The admin determined that the ACL had been applied inbound on the interface and that was the incorrect direction. How should the admin fix this issue?",
    a: [
      "Delete the original ACL and create a new ACL, applying it outbound on the interface.",
    ],
  },
  {
    q: "What characteristic of the Snort term-based subscriptions is true for both the community and the subscriber rule sets?",
    a: ["Both offer threat protection against security threats."],
  },
  {
    q: "A security analyst is configuring Snort IPS. The analyst has just downloaded and installed the Snort OVA file. What is the next step?",
    a: ["Configure Virtual Port Group interfaces."],
  },
  {
    q: "The security policy in a company specifies that employee workstations can initiate HTTP and HTTPS connections to outside websites and the return traffic is allowed. However, connections initiated from outside hosts are not allowed. Which parameter can be used in extended ACLs to meet this requirement?",
    a: ["established"],
  },
  {
    q: "A researcher is comparing the differences between a stateless firewall and a proxy firewall. Which two additional layers of the OSI model are inspected by a proxy firewall? (Choose two.)",
    a: ["Layer 5", "Layer 7"],
  },
  {
    q: "Refer to the exhibit. Which statement is true about the effect of this Cisco IOS zone-based policy firewall configuration?",
    a: [
      "The firewall will automatically allow HTTP, HTTPS, and FTP traffic from g0/0 to s0/0/0 and will track the connections. Tracking the connection allows only return traffic to be permitted through the firewall in the opposite direction.",
    ],
  },
  {
    q: "Which privilege level has the most access to the Cisco IOS?",
    a: ["level 15"],
  },
  {
    q: "Refer to the exhibit. A network administrator has configured NAT on an ASA device. What type of NAT is used?",
    a: ["inside NAT"],
  },
  {
    q: "A network analyst is configuring a site-to-site IPsec VPN. The analyst has configured both the ISAKMP and IPsec policies. What is the next step?",
    a: ["Apply the crypto map to the appropriate outbound interfaces."],
  },
  {
    q: "When an inbound Internet-traffic ACL is being implemented, what should be included to prevent the spoofing of internal networks?",
    a: ["ACEs to prevent traffic from private address spaces"],
  },
  {
    q: "Which two types of attacks are examples of reconnaissance attacks? (Choose two.)",
    a: ["port scan", "ping sweep"],
  },
  {
    q: "Which Cisco solution helps prevent ARP spoofing and ARP poisoning attacks?",
    a: ["Dynamic ARP Inspection"],
  },
  {
    q: "When the Cisco NAC appliance evaluates an incoming connection from a remote device against the defined network policies, what feature is being used?",
    a: ["posture assessment"],
  },
  {
    q: "Which two steps are required before SSH can be enabled on a Cisco router? (Choose two.)",
    a: [
      "Give the router a host name and domain name.",
      "Generate a set of secret keys to be used for encryption and decryption.",
    ],
  },
  {
    q: "The network administrator for an e-commerce website requires a service that prevents customers from claiming that legitimate orders are fake. What service provides this type of guarantee?",
    a: ["nonrepudiation"],
  },
  {
    q: "What functionality is provided by Cisco SPAN in a switched network?",
    a: [
      "It mirrors traffic that passes through a switch port or VLAN to another port for traffic analysis.",
    ],
  },
  {
    q: "Which three statements are generally considered to be best practices in the placement of ACLs? (Choose three.)",
    a: [
      "Filter unwanted traffic before it travels onto a low-bandwidth link.",
      "Place standard ACLs close to the destination IP address of the traffic.",
      "Place extended ACLs close to the source IP address of the traffic.",
    ],
  },
  {
    q: "What function is performed by the class maps configuration object in the Cisco modular policy framework?",
    a: ["identifying interesting traffic"],
  },
  {
    q: "In an attempt to prevent network attacks, cyber analysts share unique identifiable attributes of known attacks with colleagues. What three types of attributes or indicators of compromise are helpful to share? (Choose three.)",
    a: [
      "IP addresses of attack servers",
      "changes made to end system software",
      "features of malware files",
    ],
  },
  {
    q: "What two assurances does digital signing provide about code that is downloaded from the Internet? (Choose two.)",
    a: [
      "The code is authentic and is actually sourced by the publisher.",
      "The code has not been modified since it left the software publisher.",
    ],
  },
  {
    q: "Refer to the exhibit. What algorithm is being used to provide public key exchange?",
    a: ["Diffie-Hellman"],
  },
  {
    q: "Which two statements describe the use of asymmetric algorithms? (Choose two.)",
    a: [
      "If a private key is used to encrypt the data, a public key must be used to decrypt the data.",
      "If a public key is used to encrypt the data, a private key must be used to decrypt the data.",
    ],
  },
  {
    q: "Which statement is a feature of HMAC?",
    a: [
      "HMAC uses a secret key as input to the hash function, adding authentication to integrity assurance.",
    ],
  },
  {
    q: "What is the purpose of the webtype ACLs in an ASA?",
    a: ["to filter traffic for clientless SSL VPN users"],
  },
  {
    q: "Which two statements describe the effect of the access control list wildcard mask 0.0.0.15? (Choose two.)",
    a: [
      "The first 28 bits of a supplied IP address will be matched.",
      "The last four bits of a supplied IP address will be ignored.",
    ],
  },
  {
    q: "Which type of firewall is the most common and allows or blocks traffic based on Layer 3, Layer 4, and Layer 5 information?",
    a: ["stateful firewall"],
  },
  {
    q: "Which protocol or measure should be used to mitigate the vulnerability of using FTP to transfer documents between a teleworker and the company file server?",
    a: ["SCP"],
  },
  {
    q: "What tool is available through the Cisco IOS CLI to initiate security audits and to make recommended configuration changes with or without administrator input?",
    a: ["Cisco AutoSecure"],
  },
  {
    q: "Which two technologies provide enterprise-managed VPN solutions? (Choose two.)",
    a: ["site-to-site VPN", "remote access VPN"],
  },
  {
    q: "What are the three components of an STP bridge ID? (Choose three.)",
    a: [
      "the MAC address of the switch",
      "the extended system ID",
      "the bridge priority value",
    ],
  },
  {
    q: "What are two differences between stateful and packet filtering firewalls? (Choose two.)",
    a: [
      "A stateful firewall provides more stringent control over security than a packet filtering firewall.",
      "A stateful firewall will provide more logging information than a packet filtering firewall.",
    ],
  },
  {
    q: "What port state is used by 802.1X if a workstation fails authorization?",
    a: ["unauthorized"],
  },
  {
    q: "Which two characteristics apply to role-based CLI access superviews? (Choose two.)",
    a: [
      "A specific superview cannot have commands added to it directly.",
      "Users logged in to a superview can access all commands specified within the associated CLI views.",
    ],
  },
  {
    q: "What are two security features commonly found in a WAN design? (Choose two.)",
    a: [
      "firewalls protecting the main and remote sites",
      "VPNs used by mobile workers between sites",
    ],
  },
]

function _netacadNormalizeQ(s) {
  return (s || "")
    .toLowerCase()
    .replace(/[^a-z0-9 ]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
}

const _NETACAD_ANSWERS_INDEX = (() => {
  const m = new Map()
  for (const r of NETACAD_ANSWERS) m.set(_netacadNormalizeQ(r.q), r.a)
  return m
})()

function findLocalAnswers(questionText) {
  if (!questionText) return null
  const key = _netacadNormalizeQ(questionText)
  if (_NETACAD_ANSWERS_INDEX.has(key)) return _NETACAD_ANSWERS_INDEX.get(key)
  // Fallback: substring containment (handle leading prefixes like "Refer to the exhibit." etc.)
  for (const [k, v] of _NETACAD_ANSWERS_INDEX) {
    if (k.length > 40 && (k.includes(key) || key.includes(k))) return v
  }
  return null
}

if (typeof window !== "undefined") {
  window.NETACAD_ANSWERS = NETACAD_ANSWERS
  window.findLocalAnswers = findLocalAnswers
}

async function findOnlineAnswers(questionText) {
  if (
    !questionText ||
    typeof chrome === "undefined" ||
    !chrome.runtime ||
    !chrome.runtime.sendMessage
  ) {
    return null
  }
  try {
    const response = await new Promise((resolve) => {
      chrome.runtime.sendMessage(
        { action: "lookupItexam", question: questionText },
        (resp) => {
          if (chrome.runtime.lastError) {
            console.debug(
              "itexam lookup message failed:",
              chrome.runtime.lastError.message,
            )
            resolve(null)
          } else {
            resolve(resp)
          }
        },
      )
    })
    if (
      response &&
      response.ok &&
      Array.isArray(response.answers) &&
      response.answers.length > 0
    ) {
      return response.answers
    }
    if (response && response.diag) {
      console.log("[itexam diag]", response.diag)
    }
  } catch (e) {
    console.debug("itexam lookup threw:", e)
  }
  return null
}

if (typeof window !== "undefined") {
  window.findOnlineAnswers = findOnlineAnswers
}
